#!/bin/bash

ENABLE_GEMINI_REVIEW=${ENABLE_GEMINI_REVIEW:-0}

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // .tool_input.filePath // empty')

# Only review JavaScript files
if [[ ! "$FILE_PATH" =~ \.(js|jsx|mjs|cjs)$ ]] || [[ ! -f "$FILE_PATH" ]]; then
	exit 0
fi

# Exit if review is disabled
if [[ "$ENABLE_GEMINI_REVIEW" -ne 1 ]]; then
	exit 0
fi

echo "🔍 Running AI code review for modern JavaScript in $FILE_PATH..." >&2

# JavaScript-specific modern review prompt
# NOTE: If you get ModelNotFoundError or workspace errors, try:
#   cat "$FILE_PATH" | gemini -y --sandbox false -m gemini-2.5-pro -p "..."
REVIEW_OUTPUT=$(gemini -y --sandbox false -m gemini-2.5-pro -p "@$FILE_PATH Review this modern JavaScript code for:
1. ES2024+ feature usage (optional chaining, nullish coalescing, private fields)
2. Modern async patterns (async/await, Promise.allSettled, AbortController)
3. React/Vue/Svelte best practices (if applicable)
4. Performance optimizations (Web Workers, lazy loading, code splitting)
5. Security issues (prototype pollution, XSS, injection attacks)
6. Modern module patterns (ESM, dynamic imports, tree-shaking)
7. Proper error handling and defensive programming
8. Web API usage best practices (fetch, IntersectionObserver, etc.)
9. Memory leak prevention and cleanup
10. Accessibility and semantic HTML (for frontend code)
11. Modern bundler compatibility (Vite, ESBuild, SWC)
Be concise, focus on modern JavaScript patterns and critical issues only.
**Please respond in Korean (한글로 답변해주세요).**" 2>&1)

# Get project root (look for .git directory)
PROJECT_ROOT=$(git -C "$(dirname "$FILE_PATH")" rev-parse --show-toplevel 2>/dev/null || dirname "$FILE_PATH")

# Create .reviews directory structure mirroring source
RELATIVE_PATH="${FILE_PATH#$PROJECT_ROOT/}"
REVIEW_DIR="$PROJECT_ROOT/.reviews/$(dirname "$RELATIVE_PATH")"
REVIEW_FILE="$REVIEW_DIR/$(basename "$FILE_PATH").md"

mkdir -p "$REVIEW_DIR"

# Create formatted review file
cat > "$REVIEW_FILE" <<EOF
# Code Review: $RELATIVE_PATH
**Reviewed at:** $(date '+%Y-%m-%d %H:%M:%S')
**Tool:** Gemini CLI
**File:** \`$FILE_PATH\`

---

$REVIEW_OUTPUT

---
*Generated by Gemini code review hook*
EOF

# Output review to stderr so Claude can see it
echo "$REVIEW_OUTPUT" >&2
echo "📝 Review saved to: .reviews/$RELATIVE_PATH.md" >&2
echo "$REVIEW_OUTPUT" >>~/.gemini.log

# Exit with code 2 so Claude processes the stderr output
exit 2