#!/bin/bash

ENABLE_GEMINI_REVIEW=${ENABLE_GEMINI_REVIEW:-0}

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // .tool_input.filePath // empty')

# Only review Java files
if [[ ! "$FILE_PATH" =~ \.java$ ]] || [[ ! -f "$FILE_PATH" ]]; then
	exit 0
fi

# Exit if review is disabled
if [[ "$ENABLE_GEMINI_REVIEW" -ne 1 ]]; then
	exit 0
fi

echo "🔍 Running Gemini code review for $FILE_PATH..." >&2

# Java-specific review prompt
REVIEW_OUTPUT=$(gemini -p "@$FILE_PATH Review this Java code for:
1. Design patterns and best practices
2. Exception handling and error management
3. Thread safety and concurrency issues
4. Security vulnerabilities (input validation, SQL injection, etc.)
5. Performance optimizations (memory leaks, inefficient algorithms)
6. Proper use of Java idioms and modern Java features
7. Code style and readability
Be concise, only mention important issues." 2>&1)

# Get project root (look for .git directory)
PROJECT_ROOT=$(git -C "$(dirname "$FILE_PATH")" rev-parse --show-toplevel 2>/dev/null || dirname "$FILE_PATH")

# Create .reviews directory structure mirroring source
RELATIVE_PATH="${FILE_PATH#$PROJECT_ROOT/}"
REVIEW_DIR="$PROJECT_ROOT/.reviews/$(dirname "$RELATIVE_PATH")"
REVIEW_FILE="$REVIEW_DIR/$(basename "$FILE_PATH").md"

mkdir -p "$REVIEW_DIR"

# Create formatted review file
cat > "$REVIEW_FILE" <<EOF
# Code Review: $RELATIVE_PATH
**Reviewed at:** $(date '+%Y-%m-%d %H:%M:%S')
**Tool:** Gemini CLI
**File:** \`$FILE_PATH\`

---

$REVIEW_OUTPUT

---
*Generated by Gemini code review hook*
EOF

# Output review to stderr so Claude can see it
echo "$REVIEW_OUTPUT" >&2
echo "📝 Review saved to: .reviews/$RELATIVE_PATH.md" >&2
echo "$REVIEW_OUTPUT" >>~/.gemini.log

# Exit with code 2 so Claude processes the stderr output
exit 2